import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { Toaster } from "@/components/ui/sonner";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCompanyInfo } from "./actions/company";
import { getModules } from "./actions/info";
import { CompanyProvider } from "@/contexts/company-context";
import { ModulesProvider } from "@/contexts/modules-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const code = process.env.NEXT_PUBLIC_API_SLUG || "";

  const [companyRes, modulesRes] = await Promise.all([
    getCompanyInfo(code),
    getModules(),
  ]);

  const companyData = companyRes?.success ? companyRes.data : null;
  const modulesData = modulesRes?.success ? modulesRes.data : null;

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CompanyProvider initialData={companyData}>
            <ModulesProvider initialData={modulesData}>
              <Navbar />
              <main className="flex-1 flex flex-col">{children}</main>
              <Footer />
              <Toaster richColors />
            </ModulesProvider>
          </CompanyProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
